### ISSUE TITLE
deno_args are loaded empty from config file

### ISSUE THREAD

**Issue by eratio08** [eliassjogreen/denon#30]
Using a config file `.denon.json` with the content
```json
{
    "files": [
        "src/main.ts"
    ],
    "quiet": false,
    "debug": true,
    "fullscreen": true,
    "extensions": [
        ".js",
        ".ts",
        ".json"
    ],
    "interval": 500,
    "watch": [
        "src"
    ],
    "execute": {
        ".js": [
            "deno",
            "run"
        ],
        ".ts": [
            "deno",
            "run"
        ]
    },
    "deno_args": [
        "--allow-net",
        "--allow-read",
        "--lock=lock.json",
        "--lock-write"
    ],
    "fmt": true,
    "test": true
}
```
when running `denon --debug`show that the `deno_args` array is empty
```shell
[DENON] Debug enabled!
[DENON] Required permissions "read" and "run" granted
[DENON] Reading config from .denon | .denon.json | .denonrc | .denonrc.json
[DENON] Args: --debug
[DENON] Flags: {"debug":true,"help":false,"fullscreen":false,"quiet":false,"files":[],"runnerFlags":[],"deno_args":[],"fmt":false,"test":false}
[DENON] Config: {"files":["src/main.ts"],"quiet":false,"debug":true,"fullscreen":false,"extensions":[".js",".ts",".json"],"interval":500,"watch":["src"],**"deno_args":[],**"execute":{".js":["deno","run"],".ts":["deno","run"]},"fmt":false,"test":false}
[DENON] Files: /***/deno/deno-test/src/main.ts
[DENON] Paths: /***/deno/deno-test/src
[DENON] Running "deno run /***/deno/deno-test/src/main.ts"
[DENON] Creating watchers
[DENON] Creating watcher for paths "/***/deno/deno-test/src"
[DENON] Watching /***/deno/deno-test/src
error: Uncaught PermissionDenied: network access to "localhost:1234", run again with the --allow-net flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at listen ($deno$/net.ts:152:22)
    at Application.serve (server.ts:261:20)
    at Application.listen (application.ts:106:31)
    at startServer (file:///***/deno/deno-test/src/server.ts:19:13)
    at file:///***/deno/deno-test/src/main.ts:8:7
```
Seems like they get overwritten by the the default flags. `applyIfDefined` seems to do that.

**Comment by eratio08** [comment]
👍 ❤️
