### ISSUE TITLE
Deleted path

### ISSUE THREAD

**Issue by eliassjogreen** [eliassjogreen/denon#5]
If a path currently being watched is deleted the following error is thrown:
```
error: Uncaught NotFound: The system cannot find the path specified. (os error 3)
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendAsync ($deno$/dispatch_json.ts:91:10)
```
A nicer exception should be thrown by the watcher and cli should (probably) be able to handle it.

**Comment by ronhippler** [comment]
this is fixed by #18
